name: PKGBUILD CI

on:
  push:
  # schedule:
  #   - cron: '0 7 21 * *'

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fetch from AUR
      run: |
        git clone https://aur.archlinux.org/vala-panel-appmenu-xfce-git.git
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: 'vala-panel-appmenu-xfce-git'
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Package Archive
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
