name: Build vala-panel-appmenu packages

on:
  push:
  # schedule:
  #   - cron: '0 7 21 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        pacman -Sy --noconfirm --needed base-devel git meson vala
        pacman -Sy --noconfirm --needed mate-panel xfce4-panel budgie-desktop gobject-introspection
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        mkdir -p /github/artifacts
        chown builder:builder /github

    - name: Build packages
      run: |
        cd /github
        sudo -u builder git clone https://aur.archlinux.org/appmenu-glib-translator-git.git
        cd appmenu-glib-translator-git
        sudo -u builder makepkg --syncdeps --noconfirm
        rm -rf *debug*
        sudo pacman -U --noconfirm appmenu-glib-translator*.zst

    - name: Build packages
      run: |
        cd /github
        sudo -u builder git clone https://aur.archlinux.org/vala-panel-git.git
        cd vala-panel-git
        sudo -u builder makepkg --syncdeps --noconfirm
        rm -rf *debug*
        sudo pacman -U --noconfirm vala-panel*.zst

    - name: Build packages
      run: |
        cd /github
        sudo -u builder git clone https://aur.archlinux.org/appmenu-gtk-module-git.git
        cd appmenu-gtk-module-git
        sudo -u builder makepkg --syncdeps --noconfirm
        rm -rf *debug*
        sudo pacman -U --noconfirm appmenu-gtk-module*.zst

    - name: Build packages
      run: |
        cd /github
        sudo -u builder git clone https://aur.archlinux.org/vala-panel-appmenu-xfce-git.git
        cd vala-panel-appmenu-xfce-git
        sudo -u builder makepkg --syncdeps --noconfirm
        rm -rf *debug*

    - name: Upload artifacts
      run: |
        cp /github/*/*.zst /github/artifacts/
        ls -la /github/artifacts/
      shell: bash

    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vala-panel-appmenu-packages
        path: /github/artifacts/*.zst
        if-no-files-found: error
